KNOWLEDGE_FOLDER = "./knowledge"
DEFAULT_MODEL = "llama3.2"
EMBEDDING_MODEL = "nomic-embed-text"
CHUNK_SIZE = 512
CHUNK_OVERLAP = 50
TOP_K = 5

SECRET_KEY = "change-me-before-deploying"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_HOURS = 24
